[package]
name = "youmubot-osu"
version = "0.1.0"
authors = ["Natsu Kagami <natsukagami@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.7"
chrono = "0.4.10"
reqwest = "0.9.24"
serde = { version = "1.0", features = ["derive"] }
bitflags = "1"

[dev-dependencies]
serde_json = "1"
